PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO user VALUES(0,'drhareng','["ROLE_USER","ROLE_MODERATOR","ROLE_ADMIN"]','494953088180813825','arentar@gmail.com','c16a0518b100b1dca62694b004a567d0','Dr Hareng');
INSERT INTO user VALUES(1,'docteurhareng_super_spy','[]','1263869120445677641','confede.tabletop@gmail.com',NULL,'DocteurHarengSuperSpy');

INSERT INTO faction VALUES(0,'PanOceania','https://assets.corvusbelli.net/army/img/logo/factions/panoceania.svg');
INSERT INTO faction VALUES(1,'Military Orders','https://assets.corvusbelli.net/army/img/logo/factions/military-orders.svg');
INSERT INTO faction VALUES(2,'Svalarheima''s Winter Forcer','https://assets.corvusbelli.net/army/img/logo/factions/svalarheima-s-winter-force.svg');
INSERT INTO faction VALUES(3,'Kestrel Colonial Force','https://assets.corvusbelli.net/army/img/logo/factions/kestrel-colonial-force.svg');
INSERT INTO faction VALUES(4,'Yu Jing','https://assets.corvusbelli.net/army/img/logo/factions/yu-jing.svg');
INSERT INTO faction VALUES(5,'Imperial Service','https://assets.corvusbelli.net/army/img/logo/factions/imperial-service.svg');
INSERT INTO faction VALUES(6,'Invincible Army','https://assets.corvusbelli.net/army/img/logo/factions/invincible-army.svg');
INSERT INTO faction VALUES(7,'White Banner','https://assets.corvusbelli.net/army/img/logo/factions/white-banner.svg');
INSERT INTO faction VALUES(8,'Ariadna','https://assets.corvusbelli.net/army/img/logo/factions/ariadna.svg');
INSERT INTO faction VALUES(9,'Tartary Army Corps','https://assets.corvusbelli.net/army/img/logo/factions/tartary.svg');
INSERT INTO faction VALUES(10,'Kosmoflot','https://assets.corvusbelli.net/army/img/logo/factions/kosmoflot.svg');
INSERT INTO faction VALUES(11,'USAriadna Ranger Force','https://assets.corvusbelli.net/army/img/logo/factions/usariadna.svg');
INSERT INTO faction VALUES(12,'Haqqislam','https://assets.corvusbelli.net/army/img/logo/factions/haqqislam.svg');
INSERT INTO faction VALUES(13,'Hassassin Bahram','https://assets.corvusbelli.net/army/img/logo/factions/hassassin-bahram.svg');
INSERT INTO faction VALUES(14,'Qapu Khalqi','https://assets.corvusbelli.net/army/img/logo/factions/qapu-khalqi.svg');
INSERT INTO faction VALUES(15,'Ramah Taskforce','https://assets.corvusbelli.net/army/img/logo/factions/ramah-taskforce.svg');
INSERT INTO faction VALUES(16,'Nomads','https://assets.corvusbelli.net/army/img/logo/factions/nomads.svg');
INSERT INTO faction VALUES(17,'Jurisdictional Command of Corregidor','https://assets.corvusbelli.net/army/img/logo/factions/corregidor.svg');
INSERT INTO faction VALUES(18,'Jurisdictional Command of Bakunin','https://assets.corvusbelli.net/army/img/logo/factions/bakunin.svg');
INSERT INTO faction VALUES(19,'Jurisdictional Command of Tunguska','https://assets.corvusbelli.net/army/img/logo/factions/tunguska.svg');
INSERT INTO faction VALUES(20,'Combined Army','https://assets.corvusbelli.net/army/img/logo/factions/combined-army.svg');
INSERT INTO faction VALUES(21,'Morat Aggression Forces','https://assets.corvusbelli.net/army/img/logo/factions/morat.svg');
INSERT INTO faction VALUES(22,'Shasvastii Exceditionary Force','https://assets.corvusbelli.net/army/img/logo/factions/shasvastii.svg');
INSERT INTO faction VALUES(23,'Ony Contact Force','https://assets.corvusbelli.net/army/img/logo/factions/onyx.svg');
INSERT INTO faction VALUES(24,'Aleph','https://assets.corvusbelli.net/army/img/logo/factions/aleph.svg');
INSERT INTO faction VALUES(25,'Steel Phalanx','https://assets.corvusbelli.net/army/img/logo/factions/steel-phalanx.svg');
INSERT INTO faction VALUES(26,'Operations Subsection of the SSS','https://assets.corvusbelli.net/army/img/logo/factions/operations.svg');
INSERT INTO faction VALUES(27,'Tohaa','https://assets.corvusbelli.net/army/img/logo/factions/tohaa.svg');
INSERT INTO faction VALUES(28,'Druze Bayram Security','https://assets.corvusbelli.net/army/img/logo/factions/druze.svg');
INSERT INTO faction VALUES(29,'Ikari Company','https://assets.corvusbelli.net/army/img/logo/factions/ikari.svg');
INSERT INTO faction VALUES(30,'Dahshat Company','https://assets.corvusbelli.net/army/img/logo/factions/dahshat.svg');
INSERT INTO faction VALUES(31,'White Company','https://assets.corvusbelli.net/army/img/logo/factions/white-company.svg');
INSERT INTO faction VALUES(32,'O12','https://assets.corvusbelli.net/army/img/logo/factions/o-12.svg');
INSERT INTO faction VALUES(33,'Starmada, Bureau Aegis Naval Police Department','https://assets.corvusbelli.net/army/img/logo/factions/starmada.svg');
INSERT INTO faction VALUES(34,'Torchlight Brigade','https://assets.corvusbelli.net/army/img/logo/factions/torchlight-brigade.svg');
INSERT INTO faction VALUES(35,'JSA','https://assets.corvusbelli.net/army/img/logo/factions/jsa.svg');
INSERT INTO faction VALUES(36,'Shindenbutai','https://assets.corvusbelli.net/army/img/logo/factions/shindenbutai.svg');
INSERT INTO faction VALUES(37,'Ōban','https://assets.corvusbelli.net/army/img/logo/factions/oban.svg');

INSERT INTO scenario_pack VALUES(1,'La Poissonnerie','https://docs.google.com/document/d/16n_CsSi6QXnTwk-zgXyc8gyJkyj3NUF58PGswaB1zj8/edit?usp=sharing');
INSERT INTO scenario VALUES(1,1,'Age de glace',NULL);
INSERT INTO scenario VALUES(2,1,'Avant-postes',NULL);
INSERT INTO scenario VALUES(4,1,'Contrôler les communications',NULL);
INSERT INTO scenario VALUES(5,1,'Data mining',NULL);
INSERT INTO scenario VALUES(6,1,'Eglantine, ici Mirabelle !',NULL);
INSERT INTO scenario VALUES(7,1,'Epidémie',NULL);
INSERT INTO scenario VALUES(8,1,'Exfiltration',NULL);
INSERT INTO scenario VALUES(9,1,'I.A. Fantôme',NULL);
INSERT INTO scenario VALUES(10,1,'Inspection',NULL);
INSERT INTO scenario VALUES(11,1,'Largage aérien',NULL);
INSERT INTO scenario VALUES(12,1,'Le combat de l''esprit',NULL);
INSERT INTO scenario VALUES(13,1,'Ravitaillement',NULL);
INSERT INTO scenario VALUES(14,1,'Razzia',NULL);
INSERT INTO scenario VALUES(15,1,'Saboter les défenses',NULL);
INSERT INTO scenario VALUES(16,1,'Scène de crime',NULL);
COMMIT;
